apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
      - image: fametec/glpi:9.5.6
        imagePullPolicy: Always
        name: glpi
        env: 
          - name: MARIADB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mariadb-glpi-secret
                key: MYSQL_DATABASE
          - name: MARIADB_USER
            valueFrom: 
              secretKeyRef: 
                name: mariadb-glpi-secret
                key: MYSQL_USER
          - name: MARIADB_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: mariadb-glpi-secret
                key: MYSQL_PASSWORD
        envFrom:
        - configMapRef: 
            name: glpi-config
        - secretRef: 
            name: glpi-secret
        ports:
        - containerPort: 80
          name: glpi
        volumeMounts:
        - name: files-glpi-persistent-storage
          mountPath: /var/www/html/files
        - name: plugins-glpi-persistent-storage
          mountPath: /var/www/html/plugins
        - name: config-glpi-persistent-storage
          mountPath: /var/www/html/config
      volumes:
      - name: files-glpi-persistent-storage
        persistentVolumeClaim:
          claimName: files-glpi-pv-claim
      - name: plugins-glpi-persistent-storage
        persistentVolumeClaim:
          claimName: plugins-glpi-pv-claim
      - name: config-glpi-persistent-storage
        persistentVolumeClaim:
          claimName: config-glpi-pv-claim


